### ISSUE TITLE
Lack of target_copy_webgpu_binaries function

### ISSUE THREAD

**Issue by pmakal** [eliemichel/LearnWebGPU-Code#2]
_getting-started/hello-webgpu_ section mentions `target_copy_webgpu_binaries` function for copying the necessary dynamic libraries, but in the branch _step005_ _utils.cmake_ file doesn't seem to have it.

**Comment by eliemichel** [comment]
It is provided by the WebGPU distribution, i.e. in `webgpu/CMakeLists.txt` ;)

Note that since I don't have a proper mechanism to automatically keep things in sync, a more up to date version of the WebGPU directory is available here: [WebGPU-distribution](https://github.com/eliemichel/WebGPU-distribution) (but the current version should work as well)
