### ISSUE TITLE
step095-emscripten object loader warning, "Material file [ fourareen.mtl ] not found in a path :"

### ISSUE THREAD

**Issue by dennisferron** [eliemichel/LearnWebGPU-Code#29]
The App prints the warning, "Material file [ fourareen.mtl ] not found in a path :" when running the branch "step095-emscripten" as a native build using MinGW gcc (installed via MSys2, run via CLion).  The effect of not loading the material is the boat is darker and the background is black.

There's an additional argument that can be passed to tinyobj::LoadObj, "mtl_basedir".  You'd think when mtl_basedir is not passed (left default), LoadObj would use the path where the "fourareen.obj" file is to find the corresponding "fourareen.mtl" file in the same folder.  This appears not to be the case; it needs to be explicitly told where to look.

When I used filesystem::path::remove_filename() to create a value to pass for mtl_basedir, then the native build of the App is able to load the mtl file.  The effect is the boat model is lighter in shade and the background is dark gray instead of black.

Unfortunately my fix does not work on the Emscripten target:  there, it changes the warning to, "Material file [ fourareen.mtl ] not found in a path : C:/Users/dferr/CLionProjects/LearnWebGPU-Code/resources/".  A full path from my C: drive seems incorrect here.  I tried using direct strings such as RESOURCE_DIR macro or various relative paths, but they didn't work.

I notice you use ${CMAKE_CURRENT_SOURCE_DIR} to construct RESOURCE_DIR in CMakeLists.txt; CMAKE_CURRENT_SOURCE_DIR is an absolute path, and I think that gets "baked in" when you pass it to --preload-file in Emscripten.  (Uncertain, then, why the absolute path for fourareen.obj works to load it, but an absolute path for mtl_basedir fails to work for fourareen.mtl?  Might have something to do with the file api tinyobj uses, or the way it processes paths.)

I looked at an unrelated Emscripten-powered project I have which loads game files from a resource folder, and there I was using a relative path ("../res") as the argument to --preload-file.  When I changed RESOURCE_DIR and --preload-file in the LearnWebGPU-code project to use "../resources" and passed that for mtl_basedir, loading the materials worked in all 3 of my configuration targets (native debug, native release, and web).

Of course this relative dir of "../resources" is relative to how CLion instructs CMake to place build files in a cmake-build-x folder; I'm not sure how to generalize this for all situations.

**Comment by eliemichel** [comment]
The .mtl file is referenced by the .obj file, but since we do not use the information it contains, I did not share it. The warning can be ignored and has no impact (ideally I should edit the .obj so that it no longer references this .mtl file).

> When I used filesystem::path::remove_filename() to create a value to pass for mtl_basedir, then the native build of the App is able to load the mtl file. The effect is the boat model is lighter in shade and the background is dark gray instead of black.

This difference in colors comes from the fact that the surface provided by Chrome/Dawn is not in the same color space than the one provided by wgpu-native. You can address this by changing the 2.2 pow to a 1.0 at the end of the fragment shader but it is not related to the warning. You may even use [this function](https://github.com/eliemichel/WebGPU-utils/blob/main/cpp/wgpuTextureFormatGamma.cpp) to automatically figure out which value to use.

> I notice you use ${CMAKE_CURRENT_SOURCE_DIR} to construct RESOURCE_DIR in CMakeLists.txt; CMAKE_CURRENT_SOURCE_DIR is an absolute path, and I think that gets "baked in" when you pass it to --preload-file in Emscripten. (Uncertain, then, why the absolute path for fourareen.obj works to load it, but an absolute path for mtl_basedir fails to work for fourareen.mtl? Might have something to do with the file api tinyobj uses, or the way it processes paths.)

The idea of using the `RESOURCE_DIR` define is that depending on whether you build a dev version, a sharable desktop version or a web version, it is left to the build system to manage whether paths are absolute or relative so you should not have to worry about it.

In the case of emscripten, all resource files are bundled in a .data file that reproduces a mini file system. The web application cannot directly access your local files for obvious security and portability reasons. ;)
