### ISSUE TITLE
Can't compile Step030

### ISSUE THREAD

**Issue by yeti424** [eliemichel/LearnWebGPU-Code#52]
Hi,

hope this question is not too stupid, but I can't compile Step030 (and others non-vanilla ones).

Error message:

```
/Users/peter/Develop/WebGPU/Step032_Test/main.cpp:75: Fehler: call to implicitly-deleted default constructor of 'Application'
/Users/peter/Develop/WebGPU/Step032_Test/main.cpp:75:17: error: call to implicitly-deleted default constructor of 'Application'
    Application app;
                ^
/Users/peter/Develop/WebGPU/Step032_Test/main.cpp:64:18: note: default constructor of 'Application' is implicitly deleted because field 'device' has no default constructor
    wgpu::Device device;
                 ^ 
```
I'm using clang compiler on a Mac M1 Pro.
Let me know if you need more info...

Regards,
yeti

**Comment by hardcore-thinking** [comment]
Hi.

I suppose your wgpu::Device is an attribute of your Application class. If so, give your device a default value (since it's a pointer you can assign nullptr to it). The constructor needs to be able to initialize the member of the class, otherwise either you initialize them yourself by giving them a default value or you use the initialization list of the constructor (eg. `Application::Application() : device(nullptr) {}`). In your case, you could just assign nullptr to your device.

Best regards,
ajvp

**Comment by yeti424** [comment]
Hi,

this worked just fine - thanks for the help!

Best Regards,
yeti
